version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app_v1:
    image: msfidelis/chip:v1
    ports:
      - 8081:8080

  app_v2:
    image: msfidelis/chip:v2
    ports:
      - 8082:8080
